#ifndef GPU_PROPERTIES_H
#define GPU_PROPERTIES_H

#define GPU_DEFAULT_NAME            "HEXACORE vH100 CAP"
#define GPU_DEFAULT_PCI_DEVICE_ID   0x2331
#define GPU_DEFAULT_PCI_VENDOR_ID   0x10DE
#define GPU_DEFAULT_CC_MAJOR        9
#define GPU_DEFAULT_CC_MINOR        0
#define GPU_DEFAULT_SM_COUNT        132
#define GPU_DEFAULT_CORES_PER_SM    128
#define GPU_DEFAULT_TOTAL_MEM       (80ULL * 1024 * 1024 * 1024)
#define GPU_DEFAULT_FREE_MEM        (78ULL * 1024 * 1024 * 1024)
#define GPU_DEFAULT_MEM_BUS_WIDTH   5120
#define GPU_DEFAULT_L2_CACHE_SIZE   (52428800)
#define GPU_DEFAULT_ECC_ENABLED     1
#define GPU_DEFAULT_CLOCK_RATE_KHZ        1620000
#define GPU_DEFAULT_MEM_CLOCK_RATE_KHZ    1593000
#define GPU_DEFAULT_MAX_THREADS_PER_BLOCK   1024
#define GPU_DEFAULT_MAX_BLOCK_DIM_X         1024
#define GPU_DEFAULT_MAX_BLOCK_DIM_Y         1024
#define GPU_DEFAULT_MAX_BLOCK_DIM_Z         64
#define GPU_DEFAULT_MAX_GRID_DIM_X          2147483647
#define GPU_DEFAULT_MAX_GRID_DIM_Y          65535
#define GPU_DEFAULT_MAX_GRID_DIM_Z          65535
#define GPU_DEFAULT_WARP_SIZE               32
#define GPU_DEFAULT_MAX_THREADS_PER_SM      2048
#define GPU_DEFAULT_SHARED_MEM_PER_BLOCK    (49152)
#define GPU_DEFAULT_SHARED_MEM_PER_SM       (233472)
#define GPU_DEFAULT_REGS_PER_BLOCK          65536
#define GPU_DEFAULT_REGS_PER_SM             65536
#define GPU_DEFAULT_CONCURRENT_KERNELS      1
#define GPU_DEFAULT_UNIFIED_ADDRESSING      1
#define GPU_DEFAULT_MANAGED_MEMORY          1
#define GPU_DEFAULT_ASYNC_ENGINE_COUNT      3
#define GPU_DEFAULT_CAN_MAP_HOST_MEM        1
#define GPU_DEFAULT_COMPUTE_MODE            0
#define GPU_DEFAULT_INTEGRATED              0
#define GPU_DEFAULT_MULTI_GPU_BOARD         0
#define GPU_DEFAULT_COOPERATIVE_LAUNCH      1
#define GPU_DEFAULT_GLOBAL_L1_CACHE_SUPPORT 1
#define GPU_DEFAULT_LOCAL_L1_CACHE_SUPPORT  1
#define GPU_DEFAULT_MAX_TEXTURE_1D          (131072)
#define GPU_DEFAULT_MAX_TEXTURE_2D_W        (131072)
#define GPU_DEFAULT_MAX_TEXTURE_2D_H        (65536)
#define GPU_DEFAULT_MAX_TEXTURE_3D_W        (16384)
#define GPU_DEFAULT_MAX_TEXTURE_3D_H        (16384)
#define GPU_DEFAULT_MAX_TEXTURE_3D_D        (16384)
#define GPU_DEFAULT_TEXTURE_ALIGNMENT       512
#define GPU_DEFAULT_MAX_PITCH               (2147483647)
#define GPU_DEFAULT_TOTAL_CONSTANT_MEM      65536
#define GPU_DEFAULT_CLOCK_INSTRUCTION_RATE  32
#define GPU_DEFAULT_PCI_BUS_ID              0
#define GPU_DEFAULT_PCI_DEV_ID              0
#define GPU_DEFAULT_PCI_DOMAIN_ID           0
#define GPU_DEFAULT_DRIVER_VERSION          13000
#define GPU_DEFAULT_RUNTIME_VERSION         12080
#define GPU_DEFAULT_UUID_BYTES  \
    { 0x00,0x00,0x00,0x00, 0x00,0x00,0x00,0x00, \
      0x00,0x00,0x00,0x00, 0x00,0x00,0x00,0x00 }

#endif /* GPU_PROPERTIES_H */
